Repository hassio-addons/addon-traccar, pull requests merged in 2021-11, with the labels that each got.

#152 Switch to centralized GitHub Action Workflows
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/labels.yaml
  .github/workflows/lock.yaml
  .github/workflows/pr-labels.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/stale.yaml
Labels: ci

#153 Migrate JSON config to YAML
  traccar/build.json
  traccar/build.yaml
  traccar/config.json
  traccar/config.yaml
Labels: refactor

#154 ⬆️ Upgrades add-on base image to 10.2.1
  traccar/Dockerfile
  traccar/build.yaml
Labels: dependencies

#155 ⬆️ Upgrades add-on base image to 10.2.2
  traccar/Dockerfile
  traccar/build.yaml
Labels: dependencies

#122 Replace depreciated class com.mysql.jdbc.Driver
  traccar/rootfs/etc/cont-init.d/mysql.sh
Labels: bugfix

#156 Fix HTTP 415 unsupported media bug
  traccar/config.yaml
  traccar/rootfs/etc/nginx/templates/ingress.gtpl
Labels: bugfix
