Repository hassio-addons/addon-traccar, pull requests merged in 2021-02, with the labels that each got.

#62 Upgrade add-on base image to 9.1.2
  traccar/Dockerfile
  traccar/build.json
Labels: dependencies

#64 :arrow_up: Upgrades Traccar to v4.12
  traccar/Dockerfile
Labels: dependencies, minor

#69 Make transparent icon and logo with name
  traccar/icon.png
  traccar/logo.png
Labels: enhancement

#72 :arrow_up: Upgrades openjdk8-jre to 8.275.01-r0
  traccar/Dockerfile
Labels: dependencies
