Repository hassio-addons/addon-traccar, pull requests merged in 2023-03, with the labels that each got.

#201 :fireworks: Updates maintenance/license year to 2023
  LICENSE.md
  README.md
  traccar/.README.j2
  traccar/DOCS.md
Labels: maintenance

#200 Add Renovate for dependency management
  .github/dependabot.yaml
  .github/renovate.json
  traccar/Dockerfile
Labels: maintenance

#210 Sync default config with Traccar project
  traccar/rootfs/etc/traccar/hassio.xml
Labels: enhancement

#211 :books: Adjust documentation for new Traccar account set up
  traccar/DOCS.md
Labels: documentation

#212 Fix broken URL
  traccar/DOCS.md
Labels: documentation
